config:
    input_path: "C:\\Users\\vimurali\\ML\\rice-disease-classification\\input"
    image_input_path: "C:\\Users\\vimurali\\ML\\rice-disease-classification\\input\\images"
    processed_io_path: "C:\\Users\\vimurali\\ML\\rice-disease-classification\\processed_io"
    output_path: "C:\\Users\\vimurali\\ML\\rice-disease-classification\\output"
    internal_output_path: "C:\\Users\\vimurali\\ML\\rice-disease-classification\\output\\internal_output"
    visualizations_path: "C:\\Users\\vimurali\\ML\\rice-disease-classification\\visualizations"
    experimental_output_path: "C:\\Users\\vimurali\\ML\\rice-disease-classification\\experimental_logs"
    azureblob_name: "azureml-blobstore-31aeaa24-564c-4aa8-bdf4-fc4b5707bd1b"
    resource_config_path: "C:\\Users\\vimurali\\ML\\rice-disease-classification\\config.json"

model_args:
    model: 'alexnet'
    batch_size: 45
    num_epochs: 50
    lr: 0.02
    momentum: 0.9
    dropout: 0.5
    num_classes: 3
    target_cols: ['Label']
    shuffle_data: False
    refresh_data: False
    refresh_model: True
    label_dimension: 1
    output_labels: ['blast','brown', 'healthy']
                
preproc_args:
    encoding_type: 'ONEHOT_ENCODING'
    train_validation_split: 0.7
    crop_len: 224
    resize_len: 672

validation_args:
    validation_type: 'NORMAL_SPLIT'
    validation_split_share: 0.3
    k: 5